# Generated by Django 4.2 on 2023-05-25 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('numero_telephone', models.CharField(blank=True, help_text='Contact phone number', max_length=13)),
                ('image', models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to='photos/%y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=50)),
                ('adresse_etablissement', models.CharField(max_length=200)),
                ('logo', models.ImageField(null=True, upload_to='photos/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.CharField(max_length=30, null=True)),
                ('role_1', models.CharField(default='enseignant', max_length=20)),
            ],
            options={
                'verbose_name': 'Professeur',
            },
            bases=('accounts.myuser',),
        ),
        migrations.CreateModel(
            name='Faculté',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_faculté', models.CharField(max_length=50)),
                ('adresse_faculté', models.CharField(max_length=200)),
                ('spécialité', models.CharField(max_length=50)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Département',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_département', models.CharField(max_length=50)),
                ('adresse_département', models.CharField(max_length=200)),
                ('domaine_etude', models.CharField(max_length=50)),
                ('faculté', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculté')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.etablissement'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('num_inscription', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('1', '1er année'), ('2', '2éme année'), ('3', '3éme année'), ('4', '4éme année'), ('5', '5éme année')], max_length=20, null=True)),
                ('specialité', models.CharField(max_length=50)),
                ('role_1', models.CharField(default='étudiant', max_length=20)),
                ('departement', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.département')),
                ('faculté', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.faculté')),
            ],
            options={
                'verbose_name': 'Etudiant',
            },
            bases=('accounts.myuser',),
        ),
    ]
