# Generated by Django 4.2 on 2023-05-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
