# Generated by Django 4.2 on 2023-05-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role_name',
        ),
    ]
