# Generated by Django 4.2 on 2023-06-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_remove_myuser_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='role_1',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='role_1',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
    ]
