# Generated by Django 4.2 on 2023-05-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heur', models.TimeField()),
                ('lieu', models.CharField(max_length=20)),
                ('salle', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('présentiel', 'présentiel'), ('distance', 'distance')], max_length=20)),
                ('nature', models.CharField(choices=[('ouverte', 'ouverte'), ('à huis clos', 'à huis clos')], max_length=20)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_projet.projet')),
            ],
        ),
    ]
