# Generated by Django 4.2 on 2023-05-26 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='jury',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
