# Generated by Django 4.2 on 2023-06-06 14:03

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_alter_myuser_role'),
        ('planification', '0004_soutenance_invité_1_soutenance_invité_1_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='invité_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invité_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='invité_1_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=accounts.models.MyUser),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='invité_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invité_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='invité_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=accounts.models.MyUser),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='président_jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='président_jury', to='accounts.enseignant'),
        ),
    ]
