# Generated by Django 4.2 on 2023-06-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_myuser_role'),
        ('planification', '0006_remove_soutenance_jury_soutenance_co_encadreur_jury_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='co_encadreur_jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_encadreur_jury', to='accounts.enseignant'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='encadreur_jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadreur_jury', to='accounts.enseignant'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='examinataire_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exa1_jury', to='accounts.enseignant'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='examinataire_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exa2_jury', to='accounts.enseignant'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='examinataire_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exa3_jury', to='accounts.enseignant'),
        ),
    ]
