# Generated by Django 4.2 on 2023-06-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0007_alter_soutenance_co_encadreur_jury_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='invité_2',
        ),
        migrations.RemoveField(
            model_name='soutenance',
            name='invité_2_email',
        ),
    ]
