# Generated by Django 4.2 on 2023-05-25 19:21

from django.db import migrations, models
import django.db.models.deletion
import gestion_projet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nom_periode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre1_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('membre2_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('membre3_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('membre4_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('membre5_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('autorisation_soutenance', models.FileField(blank=True, default=None, null=True, upload_to='fiches_techniques/')),
                ('statut', models.CharField(blank=True, choices=[('approuvé', 'Approuvé'), ('en_attente', 'En attente'), ('rejeté', 'Rejeté')], max_length=20, null=True)),
                ('type_demande', models.CharField(choices=[('un diplôme-une startup', 'un diplôme-une startup'), ('un diplôme-un brevet', 'un diplôme-une brevet')], max_length=100)),
                ('theme', models.CharField(max_length=500)),
                ('domaine_projet', models.CharField(choices=[('Informatique', 'Informatique'), ('Social', 'Social'), ('Médcine', 'Médcine'), ('Agriculture', 'Agriculture'), ('Médicale', 'Médicale')], max_length=50)),
                ('nom_société', models.CharField(max_length=20, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='fiches_techniques/')),
                ('date_depot', models.DateField(auto_now_add=True)),
                ('co_encadreur', models.ForeignKey(blank=True, default=gestion_projet.models.get_emails_enseignants, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets_co_encadres', to='accounts.enseignant')),
                ('encadreur', models.ForeignKey(blank=True, default=gestion_projet.models.get_emails_enseignants, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets_encadres', to='accounts.enseignant')),
                ('membre1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre1_projet', to='accounts.etudiant')),
                ('membre2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre2_projet', to='accounts.etudiant')),
                ('membre3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre3_projet', to='accounts.etudiant')),
                ('membre4', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre4_projet', to='accounts.etudiant')),
                ('membre5', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre5_projet', to='accounts.etudiant')),
                ('porteur_projet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prteur_projet', to='accounts.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(blank=True, choices=[('approuvé', 'Approuvé'), ('en_attente', 'En attente'), ('rejeté', 'Rejeté')], max_length=20, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=200, null=True)),
                ('crée', models.DateTimeField(auto_now_add=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gestion_projet.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripption', models.CharField(max_length=200)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_projet.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_projet.projet')),
            ],
        ),
    ]
