# Generated by Django 4.2 on 2023-06-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recours',
        ),
    ]
