# Generated by Django 4.2 on 2023-06-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0002_delete_recours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='type_demande',
        ),
    ]
